vim.g.mapleader = " "
vim.keymap.set("n", "<leader>cd", vim.cmd.Ex)
vim.keymap.set("t", "<leader><Esc>", [[<C-\><C-n>]])
vim.keymap.set("n", "<leader>sv", ":vsplit<CR><C-w>l", { desc = "Split vertically and enter" })
vim.keymap.set("n", "<leader>sh", ":split<CR><C-w>j", { desc = "Split horizontally and enter" })
vim.keymap.set("n", "<leader>h", "<C-w>h", { desc = "Move to left window" })
vim.keymap.set("n", "<leader>j", "<C-w>j", { desc = "Move to below window" })
vim.keymap.set("n", "<leader>k", "<C-w>k", { desc = "Move to above window" })
vim.keymap.set("n", "<leader>l", "<C-w>l", { desc = "Move to right window" })
vim.keymap.set("n", "<leader>Q", "<cmd>close<CR>", { desc = "Close current window" })
